// packages/solid/playground/src/pages/Home.tsx
import { I18nT, useI18n } from '@i18n-micro/solid'
import type { Component } from 'solid-js'

const Home: Component = () => {
  const { t, tc } = useI18n()

  return (
    <div>
      <h1>{String(t('home.title'))}</h1>
      <p>{String(t('home.description'))}</p>
      <p>{String(t('greeting', { name: 'World' }))}</p>
      <p>{String(tc('apples', 5))}</p>
      <I18nT keypath="welcome" />
    </div>
  )
}

export default Home

// packages/react/playground/src/pages/Home.tsx
import { useI18n } from '@i18n-micro/react'

export function Home() {
  const { t, tc, tn, td, tdr, locale } = useI18n()

  return (
    <div>
      <h1>{String(t('home.title'))}</h1>
      <p>{String(t('home.description'))}</p>
      <p>{String(t('welcome'))}</p>
      <p>{String(t('greeting', { name: 'World' }))}</p>
      <p>{String(tc('apples', 0))}</p>
      <p>{String(tc('apples', 1))}</p>
      <p>{String(tc('apples', 5))}</p>
      <p>{String(t('number', { number: tn(1234.56) }))}</p>
      <p>{String(t('date', { date: td(new Date()) }))}</p>
      <p>{String(t('relativeDate', { relativeDate: tdr(Date.now() - 86400000) }))}</p>
      <p>Current locale: {locale}</p>
    </div>
  )
}
