// packages/solid/src/components/I18nGroup.tsx
// @ts-nocheck

import type { TranslationKey } from "@i18n-micro/types";
import { type Component, type JSX, splitProps } from "solid-js";
import { useI18nContext } from "../injection";

interface I18nGroupProps extends JSX.HTMLAttributes<HTMLDivElement> {
  prefix: string;
  groupClass?: string;
}

export const I18nGroup: Component<I18nGroupProps> = (props): JSX.Element => {
  const i18n = useI18nContext();
  const [local, others] = splitProps(props, ["prefix", "groupClass"]);

  const translate = (key: string, params?: Record<string, string | number | boolean>): string => {
    // Use type assertion for dynamic keys with prefix
    // The developer is responsible for ensuring the key exists
    const result = i18n.t(
      `${local.prefix}.${key}` as TranslationKey,
      params,
      undefined,
      i18n.getRoute(),
    );
    return typeof result === "string" ? result : String(result);
  };

  return (
    <div
      class={["i18n-group", local.groupClass].filter(Boolean).join(" ")}
      {...(others as JSX.HTMLAttributes<HTMLDivElement>)}
    >
      {typeof props.children === "function"
        ? (
            props.children as (props: {
              prefix: string;
              t: (key: string, params?: Record<string, string | number | boolean>) => string;
            }) => JSX.Element
          )({ prefix: local.prefix, t: translate })
        : props.children}
    </div>
  );
};

// packages/react/src/components/I18nGroup.tsx
import React from 'react'
import { useI18n } from '../context'
import type { TranslationKey } from '@i18n-micro/types'

export interface I18nGroupProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'children'> {
  prefix: string
  groupClass?: string
  children?: (props: { prefix: string, t: (key: string, params?: Record<string, string | number | boolean>) => string }) => React.ReactNode
}

export const I18nGroup = (props: I18nGroupProps): React.ReactElement => {
  const { prefix, groupClass, children, ...restProps } = props
  const { t, getRoute } = useI18n()

  const translate = (key: string, params?: Record<string, string | number | boolean>): string => {
    const result = t(`${prefix}.${key}` as TranslationKey, params, undefined, getRoute())
    return typeof result === 'string' ? result : String(result)
  }

  const className = ['i18n-group', groupClass].filter(Boolean).join(' ')

  return React.createElement(
    'div',
    { ...restProps, className },
    typeof children === 'function' ? children({ prefix, t: translate }) : children,
  )
}
