// packages/solid/src/components/I18nSwitcher.tsx
// @ts-nocheck

import type { Locale } from '@i18n-micro/types'
import { type Accessor, type Component, createMemo, createSignal, type JSX, onCleanup, onMount, splitProps } from 'solid-js'
import { useI18nContext, useI18nLocales, useI18nRouter } from '../injection'
import type { I18nRoutingStrategy } from '../router/types'

interface I18nSwitcherProps extends JSX.HTMLAttributes<HTMLDivElement> {
  locales?: Locale[]
  currentLocale?: string | (() => string)
  getLocaleName?: () => string | null
  switchLocale?: (locale: string) => void
  localeRoute?: (to: string | { path?: string }, locale?: string) => string | { path?: string }
  customLabels?: Record<string, string>
  customWrapperStyle?: JSX.CSSProperties
  customButtonStyle?: JSX.CSSProperties
  customDropdownStyle?: JSX.CSSProperties
  customItemStyle?: JSX.CSSProperties
  customLinkStyle?: JSX.CSSProperties
  customActiveLinkStyle?: JSX.CSSProperties
  /**
   * Inline style applied to the main switcher button when the current locale is
   * marked as `disabled: true` in locale config.
   *
   * Disabled locales are omitted from dropdown items.
   */
  customDisabledLinkStyle?: JSX.CSSProperties
  customIconStyle?: JSX.CSSProperties
}

export const I18nSwitcher: Component<I18nSwitcherProps> = (props): JSX.Element => {
  const i18n = useI18nContext()
  const router = useI18nRouter()
  const injectedLocales = useI18nLocales()

  const [local, others] = splitProps(props, [
    'locales',
    'currentLocale',
    'getLocaleName',
    'switchLocale',
    'localeRoute',
    'customLabels',
    'customWrapperStyle',
    'customButtonStyle',
    'customDropdownStyle',
    'customItemStyle',
    'customLinkStyle',
    'customActiveLinkStyle',
    'customDisabledLinkStyle',
    'customIconStyle',
  ])

  const [dropdownOpen, setDropdownOpen] = createSignal(false)
  let wrapperRef: HTMLDivElement | undefined

  const allLocales = createMemo(() => local.locales || injectedLocales || [])
  const locales = createMemo(() => allLocales().filter((locale) => !locale.disabled))
  const currentLocale = createMemo(() => {
    if (local.currentLocale !== undefined) {
      return typeof local.currentLocale === 'function' ? local.currentLocale() : local.currentLocale
    }
    // Используем реактивный accessor для отслеживания изменений
    return i18n.localeAccessor()
  })
  const currentLocaleDisabled = createMemo(() => allLocales().some((l) => l.code === currentLocale() && l.disabled))
  const currentLocaleName = createMemo(() => {
    if (local.getLocaleName) {
      return local.getLocaleName() || null
    }
    // Используем реактивный accessor для отслеживания изменений
    const current = locales().find((l) => l.code === i18n.localeAccessor())
    return current?.displayName || null
  })

  const toggleDropdown = (event?: Event) => {
    if (event) {
      event.stopPropagation()
      event.preventDefault()
    }
    setDropdownOpen(!dropdownOpen())
  }

  const localeLabel = (localeItem: Locale): string => {
    const current = local.customLabels?.[localeItem.code] || localeItem.displayName
    return current || localeItem.code
  }

  const currentLocaleLabel = createMemo(() => {
    const current = locales().find((l) => l.code === currentLocale())
    return current ? localeLabel(current) : currentLocaleName() || currentLocale()
  })

  const handleSwitchLocale = async (code: string) => {
    setDropdownOpen(false)

    if (local.switchLocale) {
      local.switchLocale(code)
      return
    }

    i18n.locale = code

    if (!router) {
      return
    }

    // Используем accessor напрямую, если доступен, иначе fallback на getCurrentPath()
    const extendedRouter = router as I18nRoutingStrategy & { getCurrentPathAccessor?: Accessor<string> }
    const currentPath = extendedRouter.getCurrentPathAccessor ? extendedRouter.getCurrentPathAccessor() : router.getCurrentPath()
    const newPath = local.localeRoute
      ? (() => {
          const res = local.localeRoute(currentPath, code)
          return typeof res === 'string' ? res : res.path || '/'
        })()
      : router?.resolvePath
        ? (() => {
            const res = router.resolvePath(currentPath, code)
            return typeof res === 'string' ? res : res.path || '/'
          })()
        : currentPath

    router.push({ path: newPath })
  }

  // Default Styles
  const wrapperStyle: JSX.CSSProperties = {
    position: 'relative',
    display: 'inline-block',
    'vertical-align': 'middle',
  }

  const buttonStyle: JSX.CSSProperties = {
    padding: '4px 12px',
    'font-size': '16px',
    cursor: 'pointer',
    'background-color': '#fff',
    border: '1px solid #333',
    transition: 'background-color 0.3s ease',
    display: 'flex',
    'align-items': 'center',
    'justify-content': 'space-between',
  }

  const dropdownStyle: JSX.CSSProperties = {
    position: 'absolute',
    top: '100%',
    left: '0',
    'z-index': 1000,
    'background-color': '#fff',
    border: '1px solid #333',
    'list-style': 'none',
    padding: '0',
    margin: '4px 0 0 0',
    'min-width': '150px',
    'box-shadow': '0 2px 8px rgba(0,0,0,0.15)',
  }

  const itemStyle: JSX.CSSProperties = {
    margin: '0',
    padding: '0',
  }

  const linkStyle: JSX.CSSProperties = {
    display: 'block',
    padding: '8px 12px',
    color: '#333',
    'text-decoration': 'none',
    transition: 'background-color 0.3s ease',
    cursor: 'pointer',
  }

  const activeLinkStyle: JSX.CSSProperties = {
    'font-weight': 'bold',
    color: '#007bff',
    cursor: 'not-allowed',
  }

  const iconStyle: JSX.CSSProperties = {
    'margin-left': '8px',
    display: 'inline-block',
    transition: 'transform 0.3s ease',
  }

  const openIconStyle: JSX.CSSProperties = {
    transform: 'rotate(180deg)',
  }

  const handleClickOutside = (event: MouseEvent) => {
    if (!dropdownOpen()) return

    const target = event.target as HTMLElement
    if (!target || !wrapperRef) return

    const isClickInside = wrapperRef.contains(target)
    const isButtonClick = target.closest('.i18n-switcher-button') !== null

    if (!isClickInside && !isButtonClick) {
      setDropdownOpen(false)
    }
  }

  onMount(() => {
    document.addEventListener('click', handleClickOutside)
  })

  onCleanup(() => {
    document.removeEventListener('click', handleClickOutside)
  })

  return (
    <div
      // @ts-expect-error - ref type conflict with Vue JSX
      ref={(el: HTMLDivElement) => {
        wrapperRef = el
      }}
      class="i18n-switcher-wrapper"
      style={{ ...wrapperStyle, ...local.customWrapperStyle }}
      {...(others as unknown as JSX.HTMLAttributes<HTMLDivElement>)}
    >
      <button
        type="button"
        class="i18n-switcher-button"
        style={{
          ...buttonStyle,
          ...local.customButtonStyle,
          ...(currentLocaleDisabled() ? local.customDisabledLinkStyle : {}),
        }}
        onClick={(e) => {
          e.preventDefault()
          e.stopPropagation()
          toggleDropdown(e)
        }}
        aria-haspopup="true"
        aria-expanded={dropdownOpen()}
      >
        <span>{currentLocaleLabel()}</span>
        <span
          style={{
            ...iconStyle,
            ...(dropdownOpen() ? openIconStyle : {}),
            ...local.customIconStyle,
          }}
        >
          ▼
        </span>
      </button>

      {dropdownOpen() && (
        <ul class="i18n-switcher-dropdown" style={{ ...dropdownStyle, ...local.customDropdownStyle }}>
          {locales().map((localeItem) => {
            const isActive = localeItem.code === currentLocale()
            // Используем accessor для реактивного отслеживания пути
            const extendedRouter = router as I18nRoutingStrategy & { getCurrentPathAccessor?: Accessor<string> }
            const currentPath = extendedRouter?.getCurrentPathAccessor
              ? extendedRouter.getCurrentPathAccessor()
              : router?.getCurrentPath() || (typeof window !== 'undefined' ? window.location.pathname : '/')
            const result = local.localeRoute
              ? local.localeRoute(currentPath, localeItem.code)
              : router?.resolvePath
                ? router.resolvePath(currentPath, localeItem.code)
                : currentPath
            const routeTo = typeof result === 'string' ? result : result?.path || '#'

            return (
              <li style={{ ...itemStyle, ...local.customItemStyle }}>
                <a
                  class={`switcher-locale-${localeItem.code}`}
                  href={typeof routeTo === 'string' ? routeTo : '#'}
                  style={{
                    ...linkStyle,
                    ...(isActive ? activeLinkStyle : {}),
                    ...local.customLinkStyle,
                    // active-specific customization wins over the generic link style
                    // (matches the React/Preact/Vue switchers)
                    ...(isActive ? local.customActiveLinkStyle : {}),
                  }}
                  onClick={(e) => {
                    e.preventDefault()
                    e.stopPropagation()
                    handleSwitchLocale(localeItem.code)
                  }}
                >
                  {localeLabel(localeItem)}
                </a>
              </li>
            )
          })}
        </ul>
      )}
    </div>
  ) as unknown as JSX.Element
}

// packages/react/src/components/I18nSwitcher.tsx
import type { Locale } from '@i18n-micro/types'
import React, { useEffect, useRef, useState } from 'react'
import { useI18n } from '../context'
import { useI18nContext, useI18nLocales, useI18nRouter } from '../injection'

function resolveCurrentLocale(prop: string | (() => string) | undefined, fallback: string): string {
  if (typeof prop === 'function') return prop()
  if (typeof prop === 'string') return prop
  return fallback
}

export interface I18nSwitcherProps extends React.HTMLAttributes<HTMLDivElement> {
  locales?: Locale[]
  currentLocale?: string | (() => string)
  getLocaleName?: () => string | null
  switchLocale?: (locale: string) => void
  localeRoute?: (to: string | { path?: string }, locale?: string) => string | { path?: string }
  customLabels?: Record<string, string>
  customWrapperStyle?: React.CSSProperties
  customButtonStyle?: React.CSSProperties
  customDropdownStyle?: React.CSSProperties
  customItemStyle?: React.CSSProperties
  customLinkStyle?: React.CSSProperties
  customActiveLinkStyle?: React.CSSProperties
  /**
   * Inline style applied to the main switcher button when the current locale is
   * marked as `disabled: true` in the locale config.
   *
   * Disabled locales are omitted from the dropdown items, but still shown as the
   * active button label.
   */
  customDisabledLinkStyle?: React.CSSProperties
  customIconStyle?: React.CSSProperties
}

export const I18nSwitcher = (props: I18nSwitcherProps): React.ReactElement => {
  const {
    locales: localesProp,
    currentLocale: currentLocaleProp,
    getLocaleName: getLocaleNameProp,
    switchLocale: switchLocaleProp,
    localeRoute: _localeRouteProp,
    customLabels = {},
    customWrapperStyle,
    customButtonStyle,
    customDropdownStyle,
    customItemStyle,
    customLinkStyle,
    customActiveLinkStyle,
    customDisabledLinkStyle = {},
    customIconStyle,
    ...restProps
  } = props

  const i18n = useI18n()
  const i18nInstance = useI18nContext()
  const router = useI18nRouter()
  const injectedLocales = useI18nLocales()
  const [dropdownOpen, setDropdownOpen] = useState(false)
  const wrapperRef = useRef<HTMLDivElement>(null)

  // Use props if provided, otherwise fallback to injected or useI18n.
  // Exclude `disabled: true` locales from the UI switcher (keep them available via getLocales for SEO).
  const allLocales = localesProp || injectedLocales || i18n.getLocales() || []
  const locales = allLocales.filter((locale) => !locale.disabled)

  const currentLocale = resolveCurrentLocale(currentLocaleProp, i18n.locale)
  const currentLocaleDisabled = allLocales.some((l) => l.code === currentLocale && l.disabled)
  const currentLocaleName = getLocaleNameProp ? getLocaleNameProp() : i18n.getLocaleName()

  const toggleDropdown = (event?: React.MouseEvent<HTMLButtonElement>) => {
    if (event) {
      event.stopPropagation()
      event.preventDefault()
    }
    setDropdownOpen(!dropdownOpen)
  }

  const localeLabel = (localeItem: Locale): string => {
    const current = customLabels[localeItem.code] || localeItem.displayName
    return current || localeItem.code
  }

  const currentLocaleLabel = (): string => {
    const current = locales.find((l) => l.code === currentLocale)
    return current ? localeLabel(current) : currentLocaleName || currentLocale
  }

  const handleSwitchLocale = (code: string) => {
    setDropdownOpen(false)
    if (switchLocaleProp) {
      switchLocaleProp(code)
      return
    }

    i18nInstance.locale = code

    if (!router) {
      return
    }

    const currentPath = router.getCurrentPath()
    const newPath = props.localeRoute
      ? (() => {
          const res = props.localeRoute(currentPath, code)
          return typeof res === 'string' ? res : res.path || '/'
        })()
      : router?.resolvePath
        ? (() => {
            const res = router.resolvePath(currentPath, code)
            return typeof res === 'string' ? res : res.path || '/'
          })()
        : currentPath

    router.push({ path: newPath })
  }

  // Default Styles
  const wrapperStyle: React.CSSProperties = {
    position: 'relative',
    display: 'inline-block',
    verticalAlign: 'middle',
  }

  const buttonStyle: React.CSSProperties = {
    padding: '4px 12px',
    fontSize: '16px',
    cursor: 'pointer',
    backgroundColor: '#fff',
    border: '1px solid #333',
    transition: 'background-color 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  }

  const dropdownStyle: React.CSSProperties = {
    position: 'absolute',
    top: '100%',
    left: '0',
    zIndex: 1000,
    backgroundColor: '#fff',
    border: '1px solid #333',
    listStyle: 'none',
    padding: '0',
    margin: '4px 0 0 0',
    minWidth: '150px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
  }

  const itemStyle: React.CSSProperties = {
    margin: '0',
    padding: '0',
  }

  const linkStyle: React.CSSProperties = {
    display: 'block',
    padding: '8px 12px',
    color: '#333',
    textDecoration: 'none',
    transition: 'background-color 0.3s ease',
    cursor: 'pointer',
  }

  const activeLinkStyle: React.CSSProperties = {
    fontWeight: 'bold',
    color: '#007bff',
    cursor: 'not-allowed',
  }

  const iconStyle: React.CSSProperties = {
    marginLeft: '8px',
    display: 'inline-block',
    transition: 'transform 0.3s ease',
  }

  const openIconStyle: React.CSSProperties = {
    transform: 'rotate(180deg)',
  }

  useEffect(() => {
    if (!dropdownOpen) return
    const handler = (event: MouseEvent) => {
      if (!dropdownOpen) return

      const target = event.target as HTMLElement
      if (!target || !wrapperRef.current) return

      const isClickInside = wrapperRef.current.contains(target)
      const isButtonClick = target.closest('.i18n-switcher-button') !== null

      if (!isClickInside && !isButtonClick) {
        setDropdownOpen(false)
      }
    }
    document.addEventListener('click', handler)
    return () => {
      document.removeEventListener('click', handler)
    }
  }, [dropdownOpen])

  const mergedWrapperStyle = { ...wrapperStyle, ...customWrapperStyle }
  const mergedButtonStyle = {
    ...buttonStyle,
    ...customButtonStyle,
    ...(currentLocaleDisabled ? customDisabledLinkStyle : {}),
  }
  const mergedDropdownStyle = { ...dropdownStyle, ...customDropdownStyle }
  const mergedItemStyle = { ...itemStyle, ...customItemStyle }
  const mergedIconStyle = {
    ...iconStyle,
    ...(dropdownOpen ? openIconStyle : {}),
    ...customIconStyle,
  }

  const dropdownItems = locales.map((localeItem) => {
    const isActive = localeItem.code === currentLocale
    const mergedLinkStyle = {
      ...linkStyle,
      ...(isActive ? activeLinkStyle : {}),
      ...customLinkStyle,
      ...(isActive ? customActiveLinkStyle : {}),
      width: '100%',
      textAlign: 'left',
      border: 'none',
      background: 'transparent',
    }

    return React.createElement(
      'li',
      {
        key: localeItem.code,
        style: mergedItemStyle,
      },
      React.createElement(
        'button',
        {
          type: 'button',
          className: `switcher-locale-${localeItem.code}`,
          style: mergedLinkStyle,
          onClick: (e: React.MouseEvent<HTMLButtonElement>) => {
            e.preventDefault()
            e.stopPropagation()
            handleSwitchLocale(localeItem.code)
          },
        },
        localeLabel(localeItem),
      ),
    )
  })

  return React.createElement(
    'div',
    {
      ref: wrapperRef,
      className: 'i18n-switcher-wrapper',
      style: mergedWrapperStyle,
      ...restProps,
    },
    React.createElement(
      'button',
      {
        type: 'button',
        className: 'i18n-switcher-button',
        style: mergedButtonStyle,
        onClick: (e: React.MouseEvent<HTMLButtonElement>) => {
          e.preventDefault()
          e.stopPropagation()
          toggleDropdown(e)
        },
        'aria-haspopup': 'true',
        'aria-expanded': dropdownOpen,
      },
      React.createElement('span', null, currentLocaleLabel()),
      React.createElement('span', { style: mergedIconStyle }, '▼'),
    ),
    dropdownOpen
      ? React.createElement(
          'ul',
          {
            className: 'i18n-switcher-dropdown',
            style: mergedDropdownStyle,
          },
          ...dropdownItems,
        )
      : null,
  ) as React.ReactElement
}
