// packages/react/src/components/I18nT.tsx
import type { PluralFunc, TranslationKey } from '@i18n-micro/types'
import React, { type JSX } from 'react'
import { useI18n } from '../context'

export interface I18nTProps extends Omit<React.HTMLAttributes<HTMLElement>, 'children'> {
  keypath: TranslationKey
  params?: Record<string, string | number | boolean>
  tag?: keyof JSX.IntrinsicElements
  plural?: number | string
  defaultValue?: string
  html?: boolean
  hideIfEmpty?: boolean
  customPluralRule?: PluralFunc
  number?: number | string
  date?: Date | string | number
  relativeDate?: Date | string | number
  children?: never // I18nT doesn't support children - translation is rendered as content
}

export const I18nT = (props: I18nTProps): React.ReactElement | null => {
  const { t, tc, tn, td, tdr, locale, getRoute } = useI18n()
  const {
    keypath,
    params,
    tag = 'span',
    plural,
    defaultValue,
    html = false,
    hideIfEmpty = false,
    customPluralRule,
    number,
    date,
    relativeDate,
    children,
    ...restProps
  } = props

  const Tag = tag as keyof JSX.IntrinsicElements
  const route = getRoute()

  // Handle number formatting
  if (number !== undefined) {
    const numberValue = Number(number)
    const formattedNumber = tn(numberValue)
    const translation = t(keypath, { number: formattedNumber, ...(params || {}) }, undefined, route)
    const content = typeof translation === 'string' ? translation : String(translation)
    if (html) {
      return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: content } }) as React.ReactElement
    }
    return React.createElement(Tag, restProps, content) as React.ReactElement
  }

  // Handle date formatting
  if (date !== undefined) {
    const formattedDate = td(date)
    const translation = t(keypath, { date: formattedDate, ...(params || {}) }, undefined, route)
    const content = typeof translation === 'string' ? translation : String(translation)
    if (html) {
      return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: content } }) as React.ReactElement
    }
    return React.createElement(Tag, restProps, content) as React.ReactElement
  }

  // Handle relative date formatting
  if (relativeDate !== undefined) {
    const formattedRelativeDate = tdr(relativeDate)
    const translation = t(keypath, { relativeDate: formattedRelativeDate, ...(params || {}) }, undefined, route)
    const content = typeof translation === 'string' ? translation : String(translation)
    if (html) {
      return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: content } }) as React.ReactElement
    }
    return React.createElement(Tag, restProps, content) as React.ReactElement
  }

  // Handle pluralization
  if (plural !== undefined) {
    const count = Number.parseInt(plural.toString(), 10)
    let translation: string
    if (customPluralRule) {
      const result = customPluralRule(
        keypath,
        count,
        params || {},
        locale,
        (k: TranslationKey, p?: Record<string, string | number | boolean>, dv?: string) => {
          const tResult = t(k, p, dv, route)
          return typeof tResult === 'string' ? tResult : String(tResult)
        },
      )
      translation = result || ''
    } else {
      translation = tc(keypath, { count, ...(params || {}) }, defaultValue)
    }
    if (html) {
      return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: translation } }) as React.ReactElement
    }
    return React.createElement(Tag, restProps, translation) as React.ReactElement
  }

  // Regular translation
  const translation = t(keypath, params, defaultValue, route)
  const content = typeof translation === 'string' ? translation : String(translation)

  if (hideIfEmpty && !content.trim()) {
    return defaultValue ? (React.createElement(React.Fragment, null, defaultValue) as React.ReactElement) : null
  }

  if (html) {
    return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: content } }) as React.ReactElement
  }

  return React.createElement(Tag, restProps, content) as React.ReactElement
}

// packages/solid/src/components/I18nT.tsx
// @ts-nocheck

import type { PluralFunc, TranslationKey } from "@i18n-micro/types";
import { type Component, createMemo, type JSX, splitProps } from "solid-js";
import { Dynamic } from "solid-js/web";
import { useI18nContext } from "../injection";

interface I18nTProps extends JSX.HTMLAttributes<HTMLElement> {
  keypath: TranslationKey;
  params?: Record<string, string | number | boolean>;
  tag?: string;
  plural?: number | string;
  defaultValue?: string;
  html?: boolean;
  hideIfEmpty?: boolean;
  customPluralRule?: PluralFunc;
  number?: number | string;
  date?: Date | string | number;
  relativeDate?: Date | string | number;
}

export const I18nT: Component<I18nTProps> = (props): JSX.Element => {
  const i18n = useI18nContext();
  const [local, others] = splitProps(props, [
    "keypath",
    "params",
    "tag",
    "plural",
    "defaultValue",
    "html",
    "hideIfEmpty",
    "customPluralRule",
    "number",
    "date",
    "relativeDate",
  ]);

  // Используем createMemo для реактивности (отслеживает изменения локали и роута)
  // В Solid мемо автоматически отслеживает зависимости при использовании в JSX
  const translation = createMemo(() => {
    // Отслеживаем изменения локали и роута через accessors
    const locale = i18n.localeAccessor();
    const route = i18n.routeAccessor();

    // Handle number formatting
    if (local.number !== undefined) {
      const numberValue = Number(local.number);
      const formattedNumber = i18n.tn(numberValue);
      const result = i18n.t(
        local.keypath,
        { number: formattedNumber, ...(local.params || {}) },
        undefined,
        route,
      );
      return typeof result === "string" ? result : String(result);
    }

    // Handle date formatting
    if (local.date !== undefined) {
      const formattedDate = i18n.td(local.date);
      const result = i18n.t(
        local.keypath,
        { date: formattedDate, ...(local.params || {}) },
        undefined,
        route,
      );
      return typeof result === "string" ? result : String(result);
    }

    // Handle relative date formatting
    if (local.relativeDate !== undefined) {
      const formattedRelativeDate = i18n.tdr(local.relativeDate);
      const result = i18n.t(
        local.keypath,
        { relativeDate: formattedRelativeDate, ...(local.params || {}) },
        undefined,
        route,
      );
      return typeof result === "string" ? result : String(result);
    }

    // Handle pluralization
    if (local.plural !== undefined) {
      const count = Number.parseInt(local.plural.toString(), 10);
      if (local.customPluralRule) {
        const translationResult = local.customPluralRule(
          local.keypath,
          count,
          local.params || {},
          locale,
          (k: TranslationKey, p?: Record<string, string | number | boolean>, dv?: string) =>
            i18n.t(k, p, dv, route),
        );
        return translationResult || "";
      } else {
        return i18n.tc(local.keypath, { count, ...(local.params || {}) }, local.defaultValue);
      }
    }

    // Regular translation
    const translationResult = (
      i18n.t(local.keypath, local.params, local.defaultValue, route) ?? ""
    ).toString();

    if (local.hideIfEmpty && !translationResult.trim()) {
      return local.defaultValue || "";
    }

    return translationResult;
  });

  // Если html=true, используем innerHTML и не рендерим children
  if (local.html) {
    return (
      <Dynamic
        component={local.tag || "span"}
        {...(others as Record<string, unknown>)}
        innerHTML={translation()}
      />
    );
  }

  // Если html=false, рендерим как текст (Solid автоматически экранирует HTML)
  const translationValue = translation();
  if (local.hideIfEmpty && !translationValue.trim()) {
    if (local.defaultValue) {
      return (
        <Dynamic component={local.tag || "span"} {...(others as Record<string, unknown>)}>
          {local.defaultValue}
        </Dynamic>
      );
    }
    return null as unknown as JSX.Element;
  }

  return (
    <Dynamic component={local.tag || "span"} {...(others as Record<string, unknown>)}>
      {translationValue}
    </Dynamic>
  );
};
