// packages/react/src/components/I18nSwitcher.tsx
import type { Locale } from '@i18n-micro/types'
import React, { useEffect, useRef, useState } from 'react'
import { useI18n } from '../context'
import { useI18nContext, useI18nLocales, useI18nRouter } from '../injection'

function resolveCurrentLocale(prop: string | (() => string) | undefined, fallback: string): string {
  if (typeof prop === 'function') return prop()
  if (typeof prop === 'string') return prop
  return fallback
}

export interface I18nSwitcherProps extends React.HTMLAttributes<HTMLDivElement> {
  locales?: Locale[]
  currentLocale?: string | (() => string)
  getLocaleName?: () => string | null
  switchLocale?: (locale: string) => void
  localeRoute?: (to: string | { path?: string }, locale?: string) => string | { path?: string }
  customLabels?: Record<string, string>
  customWrapperStyle?: React.CSSProperties
  customButtonStyle?: React.CSSProperties
  customDropdownStyle?: React.CSSProperties
  customItemStyle?: React.CSSProperties
  customLinkStyle?: React.CSSProperties
  customActiveLinkStyle?: React.CSSProperties
  customIconStyle?: React.CSSProperties
}

export const I18nSwitcher = (props: I18nSwitcherProps): React.ReactElement => {
  const {
    locales: localesProp,
    currentLocale: currentLocaleProp,
    getLocaleName: getLocaleNameProp,
    switchLocale: switchLocaleProp,
    localeRoute: _localeRouteProp,
    customLabels = {},
    customWrapperStyle,
    customButtonStyle,
    customDropdownStyle,
    customItemStyle,
    customLinkStyle,
    customActiveLinkStyle,
    customIconStyle,
    ...restProps
  } = props

  const i18n = useI18n()
  const i18nInstance = useI18nContext()
  const router = useI18nRouter()
  const injectedLocales = useI18nLocales()
  const [dropdownOpen, setDropdownOpen] = useState(false)
  const wrapperRef = useRef<HTMLDivElement>(null)

  // Use props if provided, otherwise fallback to injected or useI18n.
  // Exclude `disabled: true` locales from the UI switcher (keep them available via getLocales for SEO).
  const locales = (localesProp || injectedLocales || i18n.getLocales() || []).filter((locale) => !locale.disabled)

  const currentLocale = resolveCurrentLocale(currentLocaleProp, i18n.locale)
  const currentLocaleName = getLocaleNameProp ? getLocaleNameProp() : i18n.getLocaleName()

  const toggleDropdown = (event?: React.MouseEvent<HTMLButtonElement>) => {
    if (event) {
      event.stopPropagation()
      event.preventDefault()
    }
    setDropdownOpen(!dropdownOpen)
  }

  const localeLabel = (localeItem: Locale): string => {
    const current = customLabels[localeItem.code] || localeItem.displayName
    return current || localeItem.code
  }

  const currentLocaleLabel = (): string => {
    const current = locales.find((l) => l.code === currentLocale)
    return current ? localeLabel(current) : currentLocaleName || currentLocale
  }

  const handleSwitchLocale = (code: string) => {
    setDropdownOpen(false)
    if (switchLocaleProp) {
      switchLocaleProp(code)
      return
    }

    i18nInstance.locale = code

    if (!router) {
      return
    }

    const currentPath = router.getCurrentPath()
    const newPath = props.localeRoute
      ? (() => {
          const res = props.localeRoute(currentPath, code)
          return typeof res === 'string' ? res : res.path || '/'
        })()
      : router?.resolvePath
        ? (() => {
            const res = router.resolvePath(currentPath, code)
            return typeof res === 'string' ? res : res.path || '/'
          })()
        : currentPath

    router.push({ path: newPath })
  }

  // Default Styles
  const wrapperStyle: React.CSSProperties = {
    position: 'relative',
    display: 'inline-block',
    verticalAlign: 'middle',
  }

  const buttonStyle: React.CSSProperties = {
    padding: '4px 12px',
    fontSize: '16px',
    cursor: 'pointer',
    backgroundColor: '#fff',
    border: '1px solid #333',
    transition: 'background-color 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  }

  const dropdownStyle: React.CSSProperties = {
    position: 'absolute',
    top: '100%',
    left: '0',
    zIndex: 1000,
    backgroundColor: '#fff',
    border: '1px solid #333',
    listStyle: 'none',
    padding: '0',
    margin: '4px 0 0 0',
    minWidth: '150px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
  }

  const itemStyle: React.CSSProperties = {
    margin: '0',
    padding: '0',
  }

  const linkStyle: React.CSSProperties = {
    display: 'block',
    padding: '8px 12px',
    color: '#333',
    textDecoration: 'none',
    transition: 'background-color 0.3s ease',
    cursor: 'pointer',
  }

  const activeLinkStyle: React.CSSProperties = {
    fontWeight: 'bold',
    color: '#007bff',
    cursor: 'not-allowed',
  }

  const iconStyle: React.CSSProperties = {
    marginLeft: '8px',
    display: 'inline-block',
    transition: 'transform 0.3s ease',
  }

  const openIconStyle: React.CSSProperties = {
    transform: 'rotate(180deg)',
  }

  useEffect(() => {
    if (!dropdownOpen) return
    const handler = (event: MouseEvent) => {
      if (!dropdownOpen) return

      const target = event.target as HTMLElement
      if (!target || !wrapperRef.current) return

      const isClickInside = wrapperRef.current.contains(target)
      const isButtonClick = target.closest('.i18n-switcher-button') !== null

      if (!isClickInside && !isButtonClick) {
        setDropdownOpen(false)
      }
    }
    document.addEventListener('click', handler)
    return () => {
      document.removeEventListener('click', handler)
    }
  }, [dropdownOpen])

  const mergedWrapperStyle = { ...wrapperStyle, ...customWrapperStyle }
  const mergedButtonStyle = { ...buttonStyle, ...customButtonStyle }
  const mergedDropdownStyle = { ...dropdownStyle, ...customDropdownStyle }
  const mergedItemStyle = { ...itemStyle, ...customItemStyle }
  const mergedIconStyle = {
    ...iconStyle,
    ...(dropdownOpen ? openIconStyle : {}),
    ...customIconStyle,
  }

  const dropdownItems = locales.map((localeItem) => {
    const isActive = localeItem.code === currentLocale
    const mergedLinkStyle = {
      ...linkStyle,
      ...(isActive ? activeLinkStyle : {}),
      ...customLinkStyle,
      ...(isActive ? customActiveLinkStyle : {}),
      width: '100%',
      textAlign: 'left',
      border: 'none',
      background: 'transparent',
    }

    return React.createElement(
      'li',
      {
        key: localeItem.code,
        style: mergedItemStyle,
      },
      React.createElement(
        'button',
        {
          type: 'button',
          className: `switcher-locale-${localeItem.code}`,
          style: mergedLinkStyle,
          onClick: (e: React.MouseEvent<HTMLButtonElement>) => {
            e.preventDefault()
            e.stopPropagation()
            handleSwitchLocale(localeItem.code)
          },
        },
        localeLabel(localeItem),
      ),
    )
  })

  return React.createElement(
    'div',
    {
      ref: wrapperRef,
      className: 'i18n-switcher-wrapper',
      style: mergedWrapperStyle,
      ...restProps,
    },
    React.createElement(
      'button',
      {
        type: 'button',
        className: 'i18n-switcher-button',
        style: mergedButtonStyle,
        onClick: (e: React.MouseEvent<HTMLButtonElement>) => {
          e.preventDefault()
          e.stopPropagation()
          toggleDropdown(e)
        },
        ariaHaspopup: 'true',
        ariaExpanded: dropdownOpen,
      },
      React.createElement('span', null, currentLocaleLabel()),
      React.createElement('span', { style: mergedIconStyle }, '▼'),
    ),
    dropdownOpen
      ? React.createElement(
          'ul',
          {
            className: 'i18n-switcher-dropdown',
            style: mergedDropdownStyle,
          },
          ...dropdownItems,
        )
      : null,
  ) as React.ReactElement
}

// src/runtime/components/i18n-switcher.vue
<template>
  <div :style="[wrapperStyle, customWrapperStyle]">
    <slot name="before-button" />

    <button class="language-switcher" :style="[buttonStyle, customButtonStyle]" @click="toggleDropdown">
      <slot name="before-selected-locale" />
      {{ currentLocaleLabel }}
      <slot name="after-selected-locale" />
      <span :style="[iconStyle, dropdownOpen ? openIconStyle : {}, customIconStyle]">&#9662;</span>
    </button>

    <slot name="before-dropdown" />

    <ul v-show="dropdownOpen" :style="[dropdownStyle, customDropdownStyle]">
      <slot name="before-dropdown-items" />

      <li v-for="locale in locales" :key="locale.code" :style="[itemStyle, customItemStyle]">
        <slot name="before-item" :locale="locale" />

        <NuxtLink
          :class="`switcher-locale-${locale.code}`"
          :to="switchLocaleRoute(locale.code)"
          :style="[
            linkStyle,
            locale.code === currentLocale ? activeLinkStyle : {},
            locale.code === currentLocale ? customActiveLinkStyle : {},
            customLinkStyle,
          ]"
          :hreflang="locale.iso || locale.code"
          @click="switchLocale(locale.code)"
        >
          <slot name="before-link-content" :locale="locale" />
          {{ localeLabel(locale) }}
          <slot name="after-link-content" :locale="locale" />
        </NuxtLink>

        <slot name="after-item" :locale="locale" />
      </li>

      <slot name="after-dropdown-items" />
    </ul>

    <slot name="after-dropdown" />
  </div>
</template>

<script lang="ts" setup>
import type { CSSProperties } from 'vue'
import { computed, ref } from 'vue'
import { useNuxtApp } from '#imports'

type LocaleCode = string
interface Locale {
  code: LocaleCode
  disabled?: boolean
  iso?: string
  dir?: 'ltr' | 'rtl' | 'auto'
  displayName?: string
  baseUrl?: string
  baseDefault?: boolean
  [key: string]: unknown
}

interface Props {
  customLabels?: Record<string, string>
  customWrapperStyle?: CSSProperties
  customButtonStyle?: CSSProperties
  customDropdownStyle?: CSSProperties
  customItemStyle?: CSSProperties
  customLinkStyle?: CSSProperties
  customActiveLinkStyle?: CSSProperties
  customIconStyle?: CSSProperties
}

const props = withDefaults(defineProps<Props>(), {
  customLabels: () => ({}),
  customWrapperStyle: () => ({}),
  customButtonStyle: () => ({}),
  customDropdownStyle: () => ({}),
  customItemStyle: () => ({}),
  customLinkStyle: () => ({}),
  customActiveLinkStyle: () => ({}),
  customIconStyle: () => ({}),
})

const { $switchLocaleRoute, $switchLocale, $getLocales, $getLocale, $getLocaleName } = useNuxtApp()
// Keep `$getLocales()` complete for SEO/meta; the switcher only shows switchable locales.
const locales = computed(() => ($getLocales() ?? []).filter((locale: Locale) => !locale.disabled))
const currentLocale = computed(() => $getLocale())
const currentLocaleName = computed(() => $getLocaleName())
const dropdownOpen = ref(false)

const toggleDropdown = () => {
  dropdownOpen.value = !dropdownOpen.value
}

const switchLocaleRoute = (code: string) => {
  return $switchLocaleRoute(code)
}

const localeLabel = (locale: Locale) => {
  const current = props.customLabels[locale.code] || locale.displayName
  if (!current) {
    console.warn('[i18n-switcher] Either define a custom label for the locale or provide a displayName in the nuxt.config.i18n')
  }
  return current
}

const currentLocaleLabel = computed(() =>
  localeLabel({
    code: currentLocale.value,
    displayName: currentLocaleName.value ?? undefined,
  }),
)

const switchLocale = (code: string) => {
  toggleDropdown()
  $switchLocale(code)
}

// Default Styles
const wrapperStyle: CSSProperties = {
  position: 'relative',
  display: 'inline-block',
}

const buttonStyle: CSSProperties = {
  padding: '4px 12px',
  fontSize: '16px',
  cursor: 'pointer',
  backgroundColor: '#fff',
  border: '1px solid #333',
  transition: 'background-color 0.3s ease',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
}

const dropdownStyle: CSSProperties = {
  position: 'absolute',
  top: '100%',
  left: '0',
  zIndex: '10',
  backgroundColor: '#fff',
  border: '1px solid #333',
  listStyle: 'none',
  padding: '0',
  margin: '4px 0 0 0',
}

const itemStyle: CSSProperties = {
  margin: '0',
  padding: '0',
}

const linkStyle: CSSProperties = {
  display: 'block',
  padding: '8px 12px',
  color: '#333',
  textDecoration: 'none',
  transition: 'background-color 0.3s ease',
}

const activeLinkStyle: CSSProperties = {
  fontWeight: 'bold',
  color: '#007bff',
  // Current locale is not a meaningful switch target
  cursor: 'not-allowed',
}

const iconStyle: CSSProperties = {
  marginLeft: '8px',
  transition: 'transform 0.3s ease',
}

const openIconStyle: CSSProperties = {
  transform: 'rotate(180deg)',
}
</script>
