// packages/react/src/components/I18nT.tsx
import type { PluralFunc, TranslationKey } from '@i18n-micro/types'
import React, { type JSX } from 'react'
import { useI18n } from '../context'

export interface I18nTProps extends Omit<React.HTMLAttributes<HTMLElement>, 'children'> {
  keypath: TranslationKey
  params?: Record<string, string | number | boolean>
  tag?: keyof JSX.IntrinsicElements
  plural?: number | string
  defaultValue?: string
  html?: boolean
  hideIfEmpty?: boolean
  customPluralRule?: PluralFunc
  number?: number | string
  date?: Date | string | number
  relativeDate?: Date | string | number
  children?: never // I18nT doesn't support children - translation is rendered as content
}

export const I18nT = (props: I18nTProps): React.ReactElement | null => {
  const { t, tc, tn, td, tdr, locale, getRoute } = useI18n()
  const {
    keypath,
    params,
    tag = 'span',
    plural,
    defaultValue,
    html = false,
    hideIfEmpty = false,
    customPluralRule,
    number,
    date,
    relativeDate,
    children,
    ...restProps
  } = props

  const Tag = tag as keyof JSX.IntrinsicElements
  const route = getRoute()

  // Handle number formatting
  if (number !== undefined) {
    const numberValue = Number(number)
    const formattedNumber = tn(numberValue)
    const translation = t(keypath, { number: formattedNumber, ...(params || {}) }, undefined, route)
    const content = typeof translation === 'string' ? translation : String(translation)
    if (html) {
      return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: content } }) as React.ReactElement
    }
    return React.createElement(Tag, restProps, content) as React.ReactElement
  }

  // Handle date formatting
  if (date !== undefined) {
    const formattedDate = td(date)
    const translation = t(keypath, { date: formattedDate, ...(params || {}) }, undefined, route)
    const content = typeof translation === 'string' ? translation : String(translation)
    if (html) {
      return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: content } }) as React.ReactElement
    }
    return React.createElement(Tag, restProps, content) as React.ReactElement
  }

  // Handle relative date formatting
  if (relativeDate !== undefined) {
    const formattedRelativeDate = tdr(relativeDate)
    const translation = t(keypath, { relativeDate: formattedRelativeDate, ...(params || {}) }, undefined, route)
    const content = typeof translation === 'string' ? translation : String(translation)
    if (html) {
      return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: content } }) as React.ReactElement
    }
    return React.createElement(Tag, restProps, content) as React.ReactElement
  }

  // Handle pluralization
  if (plural !== undefined) {
    const count = Number.parseInt(plural.toString(), 10)
    let translation: string
    if (customPluralRule) {
      const result = customPluralRule(
        keypath,
        count,
        params || {},
        locale,
        (k: TranslationKey, p?: Record<string, string | number | boolean>, dv?: string) => {
          const tResult = t(k, p, dv, route)
          return typeof tResult === 'string' ? tResult : String(tResult)
        },
      )
      translation = result || ''
    } else {
      translation = tc(keypath, { count, ...(params || {}) }, defaultValue)
    }
    if (html) {
      return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: translation } }) as React.ReactElement
    }
    return React.createElement(Tag, restProps, translation) as React.ReactElement
  }

  // Regular translation
  const translation = t(keypath, params, defaultValue, route)
  const content = typeof translation === 'string' ? translation : String(translation)

  if (hideIfEmpty && !content.trim()) {
    return defaultValue ? (React.createElement(React.Fragment, null, defaultValue) as React.ReactElement) : null
  }

  if (html) {
    return React.createElement(Tag, { ...restProps, dangerouslySetInnerHTML: { __html: content } }) as React.ReactElement
  }

  return React.createElement(Tag, restProps, content) as React.ReactElement
}

// src/runtime/components/i18n-t.vue
<script lang="ts">
import { h as hyperscript, defineComponent } from 'vue'
import type { VNode, PropType } from 'vue'
import type { PluralFunc } from '@i18n-micro/types'
import type { PluginsInjections } from '../../runtime/plugins/01.plugin'
import { useNuxtApp, useRoute } from '#imports'

export default defineComponent({
  name: 'I18nT',
  props: {
    keypath: {
      type: String as PropType<string>,
      required: true,
    },
    plural: {
      type: [Number, String] as PropType<number | string>,
    },
    tag: {
      type: String as PropType<string>,
      default: 'span',
    },
    params: {
      type: Object as PropType<Record<string, string | number | boolean>>,
      default: () => ({}),
    },
    defaultValue: {
      type: String as PropType<string>,
      default: '',
    },
    html: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    hideIfEmpty: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    customPluralRule: {
      type: Function as PropType<PluralFunc>,
      default: null,
    },
    number: {
      type: [Number, String] as PropType<number | string>,
    },
    date: {
      type: [Date, String, Number] as PropType<Date | string | number>,
    },
    relativeDate: {
      type: [Date, String, Number] as PropType<Date | string | number>,
    },
  },
  setup(props, { slots, attrs }) {
    return () => {
      const options: Record<string, string | number | boolean> = {}

      const { $getLocale, $_t, $tc, $tn, $td, $tdr } = useNuxtApp() as unknown as PluginsInjections
      const route = useRoute()
      const $t = $_t(route)

      if (props.number !== undefined) {
        const numberValue = Number(props.number)
        return hyperscript(props.tag, { ...attrs, innerHTML: $t(props.keypath, { number: $tn(numberValue) }) })
      }

      if (props.date !== undefined) {
        return hyperscript(props.tag, { ...attrs, innerHTML: $t(props.keypath, { date: $td(props.date) }) })
      }

      if (props.relativeDate !== undefined) {
        return hyperscript(props.tag, { ...attrs, innerHTML: $t(props.keypath, { relativeDate: $tdr(props.relativeDate) }) })
      }

      if (props.plural !== undefined) {
        const count = Number.parseInt(props.plural.toString())
        if (props.customPluralRule) {
          return hyperscript(props.tag, { ...attrs, innerHTML: props.customPluralRule(
            props.keypath,
            count,
            props.params,
            $getLocale(),
            $t,
          ) })
        }
        else {
          return hyperscript(props.tag, { ...attrs, innerHTML: $tc(props.keypath, { count, ...props.params }) })
        }
      }

      const translation = ($t(props.keypath, { ...props.params, ...options }) ?? '').toString()

      if (props.hideIfEmpty && !translation.trim()) {
        return props.defaultValue ?? null
      }

      if (props.html) {
        return hyperscript(props.tag, { ...attrs, innerHTML: translation })
      }

      if (slots.default) {
        return hyperscript(
          props.tag,
          attrs,
          slots.default({ translation }),
        )
      }

      const children: (string | VNode)[] = []
      let lastIndex = 0

      for (const [slotName, slotFn] of Object.entries(slots)) {
        const placeholder = `{${slotName}}`
        const index = translation.indexOf(placeholder, lastIndex)

        if (index !== -1) {
          if (index > lastIndex) {
            children.push(translation.slice(lastIndex, index))
          }

          children.push(hyperscript(slotFn!))

          lastIndex = index + placeholder.length
        }
      }

      if (lastIndex < translation.length) {
        children.push(translation.slice(lastIndex))
      }

      if (slots.default) {
        return hyperscript(
          props.tag,
          attrs,
          slots.default({ children }),
        )
      }

      return hyperscript(props.tag, attrs, children)
    }
  },
})
</script>
